# Generated by Django 6.0.2 on 2026-04-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Заказано(литры)'),
        ),
    ]
