# Generated by Django 6.0.2 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_feedback_comment_alter_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='honey',
            name='picture',
            field=models.ImageField(null=True, upload_to='honey', verbose_name='Изображение'),
        ),
    ]
