# Generated by Django 6.0.2 on 2026-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0003_honey_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(null=True, upload_to='feedback', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(null=True, upload_to='groups', verbose_name='Изображение'),
        ),
    ]
